export const mockTasks = [
  {
    id: "1",
    wbs: "1",
    task: "New Project",
    resource: "",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "2",
    wbs: "2",
    task: "",
    resource: "",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "3",
    wbs: "3",
    task: "",
    resource: "",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
];
