import { TaskRow } from "@/types/tasks";

export const mockTasks: TaskRow[] = [
  {
    id: "1",
    wbs: "1",
    task: "Task A",
    resource: "Alex",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "2",
    wbs: "2",
    task: "Task B",
    resource: "Jordan",
    status: "In Progress",
    start: "",
    finish: "",
    percentComplete: 20,
  },
  {
    id: "3",
    wbs: "3",
    task: "Task C",
    resource: "Sam",
    status: "Complete",
    start: "",
    finish: "",
    percentComplete: 100,
  },
  {
    id: "4",
    wbs: "4",
    task: "Task D",
    resource: "Taylor",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "5",
    wbs: "5",
    task: "Task E",
    resource: "Morgan",
    status: "Past Due",
    start: "",
    finish: "",
    percentComplete: 50,
  },
  {
    id: "6",
    wbs: "6",
    task: "Task F",
    resource: "Chris",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "7",
    wbs: "7",
    task: "Task G",
    resource: "Alex",
    status: "In Progress",
    start: "",
    finish: "",
    percentComplete: 30,
  },
  {
    id: "8",
    wbs: "8",
    task: "Task H",
    resource: "Jordan",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "9",
    wbs: "9",
    task: "Task I",
    resource: "Sam",
    status: "Complete",
    start: "",
    finish: "",
    percentComplete: 100,
  },
  {
    id: "10",
    wbs: "10",
    task: "Task J",
    resource: "Taylor",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "11",
    wbs: "11",
    task: "Task K",
    resource: "Morgan",
    status: "Past Due",
    start: "",
    finish: "",
    percentComplete: 60,
  },
  {
    id: "12",
    wbs: "12",
    task: "Task L",
    resource: "Chris",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "13",
    wbs: "13",
    task: "Task M",
    resource: "Alex",
    status: "In Progress",
    start: "",
    finish: "",
    percentComplete: 40,
  },
  {
    id: "14",
    wbs: "14",
    task: "Task N",
    resource: "Jordan",
    status: "Not Started",
    start: "",
    finish: "",
    percentComplete: 0,
  },
  {
    id: "15",
    wbs: "15",
    task: "Task O",
    resource: "Sam",
    status: "Complete",
    start: "",
    finish: "",
    percentComplete: 100,
  },
];
